### ISSUE TITLE
module export is incorrect

### ISSUE THREAD

**Issue by natew** [PabloSzx/new_gqless#1]
The "module" export in package.json points to a file that doesn't exist:

<img width="853" alt="image" src="https://user-images.githubusercontent.com/12100/108121797-968e1f80-7060-11eb-8dcc-69cc5b7501a2.png">

**Comment by PabloSzx** [comment]
fixing it, thanks

**Comment by PabloSzx** [comment]
fixed, and published gqless@3.0.7 gqless-cli@4.0.1 gqless-react@2.0.7
